/* AUTO-GENERATED by scripts/generate-dataset-registry.ts. DO NOT EDIT. */
export type CacheFillFallback = 'return_null' | 'hedge' | 'throw';
export interface CacheFillRegistryEntry {
  logicalName: string;
  leaseMs: number;
  waitMs: number;
  pollMinMs: number;
  pollMaxMs: number;
  fallback: CacheFillFallback;
}
export const CACHE_FILL_REGISTRY: Record<string, CacheFillRegistryEntry> = {};
